# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page_Gestionnaire_Enclos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(213, 246)
        self.pushButton_Ajouter = QtWidgets.QPushButton(Dialog)
        self.pushButton_Ajouter.setGeometry(QtCore.QRect(0, 90, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Ajouter.setFont(font)
        self.pushButton_Ajouter.setObjectName("pushButton_Ajouter")
        self.pushButton_Modifier = QtWidgets.QPushButton(Dialog)
        self.pushButton_Modifier.setGeometry(QtCore.QRect(0, 140, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Modifier.setFont(font)
        self.pushButton_Modifier.setObjectName("pushButton_Modifier")
        self.pushButton_Supprimer = QtWidgets.QPushButton(Dialog)
        self.pushButton_Supprimer.setGeometry(QtCore.QRect(0, 190, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Supprimer.setFont(font)
        self.pushButton_Supprimer.setObjectName("pushButton_Supprimer")
        self.comboBox_Enclos = QtWidgets.QComboBox(Dialog)
        self.comboBox_Enclos.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.comboBox_Enclos.setObjectName("comboBox_Enclos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_Ajouter.setText(_translate("Dialog", "Ajouter"))
        self.pushButton_Modifier.setText(_translate("Dialog", "modifier"))
        self.pushButton_Supprimer.setText(_translate("Dialog", "supprimer"))
